GET http://localhost:8080/employees
###

GET http://localhost:8080/employees/get?position=Software%20Engineer
###

POST http://localhost:8080/employees/add
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "hireDate": "2021-01-01",
    "position": "Software Engineer"
}
###

POST http://localhost:8080/employees/add
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "hireDate": "2021-01-01",
    "position": "Software Engineer"
}
###

PUT http://localhost:8080/employees/3
Content-Type: application/json

{
    "position": "Software Engineer II"
}
###
