GET http://localhost:3000/empl/hello
###

GET http://localhost:3000/empl/
###


GET http://localhost:3000/empl/get/8
###

GET http://localhost:3000/empl/query?position=Senior%20Software%20Engineer
###

POST http://localhost:3000/empl/
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "hireDate": "2021-01-01",
    "position": "Software Engineer"
}
###

PUT http://localhost:3000/empl/position/9
Content-Type: application/json

{
    "position": "Senior Software Engineer"
}
###